apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-modelmesh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-modelmesh
    app.kubernetes.io/part-of: modelmeshserving
  name: odh-modelmesh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: odh-modelmesh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: odh-modelmesh
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/modelmeshserving/odh-modelmesh@sha256:ec200331548b9553bbdb358b0efe382b8559fff3d199b9cc66e07cde4ffa7e12
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
